inference:
  _target_: torch.utils.data.ConcatDataset # we can concat datasets if we want to
  datasets:
    - _target_: src.datasets.CustomDataset_train
      instance_transforms: ${transforms.instance_transforms.train}
      limit: 1000