inference:
  _target_: torch.utils.data.ConcatDataset
  datasets:
    - _target_: src.datasets.CustomDataset_test
      instance_transforms: ${transforms.instance_transforms.train}
      limit: 20