train:
  _target_: torch.utils.data.ConcatDataset
  datasets:
    - _target_: src.datasets.CustomDataset_train
      instance_transforms: ${transforms.instance_transforms.train}
      limit: 100
val:
  _target_: torch.utils.data.ConcatDataset
  datasets:
    - _target_: src.datasets.CustomDataset_val
      instance_transforms: ${transforms.instance_transforms.train}
      limit: 100