# ESRT model
_target_: src.model.ESRT
upscale: 2

# SwinIR model
#_target_: src.model.SwinIR
#upscale: 2
#img_size: 64
#window_size: 8
#img_range: 1.
#depths: [6, 6, 6, 6]
#embed_dim: 60
#num_heads: [6, 6, 6, 6]
#mlp_ratio: 2
#upsampler: 'pixelshuffledirect'

# Swin2SR model (Swin2SR_Lightweight_X2_64)
#_target_: src.model.Swin2SR
#upscale: 2
#in_chans: 3
#img_size: 64
#window_size: 8
#img_range: 1.
#depths: [6, 6, 6, 6]
#embed_dim: 60
#num_heads: [6, 6, 6, 6]
#mlp_ratio: 2
#upsampler: 'pixelshuffledirect'
#resi_connection: '1conv'

# Swin2SR model (Swin2SR_CompressedSR_X4_48)
#_target_: src.model.Swin2SR
#upscale: 4
#in_chans: 3
#img_size: 48
#window_size: 8
#img_range: 1.
#depths: [6, 6, 6, 6, 6, 6]
#embed_dim: 180
#num_heads: [6, 6, 6, 6, 6, 6]
#mlp_ratio: 2
#upsampler: 'pixelshuffle_aux'
#resi_connection: '1conv'