device: "auto"
train: # metrics that are calculated during training
  - _target_: src.metrics.PSNRMetric
    name: "TRAIN_PSNR"
    device: "auto"
  - _target_: src.metrics.SSIMMetric
    name: "TRAIN_SSIM"
    device: "auto"
  - _target_: src.metrics.ContentLossMetric
    name: "TRAIN_ContentLoss"
    device: "auto"
inference: # metrics that are calculated during training
  - _target_: src.metrics.PSNRMetric
    name: "TRAIN_PSNR"
    device: "auto"
  - _target_: src.metrics.SSIMMetric
    name: "TRAIN_SSIM"
    device: "auto"
  - _target_: src.metrics.ContentLossMetric
    name: "TRAIN_ContentLoss"
    device: "auto"