device: "auto"
inference:
  - _target_: src.metrics.PSNRMetric
    name: "PSNR"
    device: "auto"
  - _target_: src.metrics.SSIMMetric
    name: "SSIM"
    device: "auto"
  - _target_: src.metrics.ContentLossMetric
    name: "ContentLoss"
    device: "auto"
  - _target_: src.metrics.LPIPSMetric
    name: "LPIPSMetric"
    device: "auto"