device: "auto"
train: # metrics that are calculated during training
  - _target_: src.metrics.PSNRMetric
    name: "PSNR"
    device: "auto"
  - _target_: src.metrics.SSIMMetric
    name: "SSIM"
    device: "auto"
  - _target_: src.metrics.ContentLossMetric
    name: "ContentLoss"
    device: "auto"
inference: # metrics that are calculated during training
  - _target_: src.metrics.PSNRMetric
    name: "PSNR"
    device: "auto"
  - _target_: src.metrics.SSIMMetric
    name: "SSIM"
    device: "auto"
  - _target_: src.metrics.ContentLossMetric
    name: "ContentLoss"
    device: "auto"