train:
  data_object: # name of the tensor on which we apply transform
    _target_: torch.nn.Sequential # to apply several transforms sequentially
inference:
  data_object: # name of the tensor on which we apply transform
    _target_: torch.nn.Sequential # to apply several transforms sequentially