from src.degradation.degradation_APISR import ImageDegradationPipeline_APISR
from src.degradation.degradation_RealESRGAN import ImageDegradationPipeline_RealESRGAN
from src.degradation.degradation_jpeg import ImageDegradationPipeline_base
from src.degradation.degradation_custom import ImageDegradationPipeline_custom
from src.degradation.degradation_custom_v2 import ImageDegradationPipeline_custom_v2