from src.degradation.degradation_APISR import ImageDegradationPipeline_APISR
from src.degradation.degradation_RealESRGAN import ImageDegradationPipeline_RealESRGAN
from src.degradation.degradation_jpeg import ImageDegradationPipeline_base