_target_: src.degradation.ImageDegradationPipeline_RealESRGAN
kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
kernel_prob: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
blur_sigma: [0.1, 10]
betag_range: [0.5, 4]
betap_range: [1, 2]
sinc_prob: 0.1

second_blur_prob: 0.3
kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
kernel_prob2: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
blur_sigma2: [0.1, 3]
betag_range2: [0.5, 4]
betap_range2: [1, 2]
sinc_prob2: 0.1

final_sinc_prob: 0.2

mode: "batch"
device: "cuda"