_target_: src.degradation.ImageDegradationPipeline_custom
device: "cuda"
scale: 2

# Минимизация параметров
intermittent_edges_prob: 0.5
rainbow_effects_prob: 0.5
rainbow_effects_edge_width: 15
rainbow_effects_edge_threshold: [10, 50]
rainbow_effects_channel_shift: [10, 180]
rainbow_effects_pixel_randomness_rate: 0.3
intermittent_edges_canny_thresholds: [30, 150]
intermittent_edges_length_range: [2, 7]
intermittent_edges_color_shift_range: [-30, 30]
kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
kernel_prob: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
sinc_prob: 0.1
blur_sigma: [0.1, 0.5]
betag_range: [0.1, 0.5]
betap_range: [0.1, 0.5]

# Вторая группа параметров
intermittent_edges_prob2: 0.5
rainbow_effects_prob2: 0.5
rainbow_effects_edge_width2: 15
rainbow_effects_edge_threshold2: [10, 50]
rainbow_effects_channel_shift2: [10, 180]
rainbow_effects_pixel_randomness_rate2: 0.3
intermittent_edges_canny_thresholds2: [30, 100]
intermittent_edges_length_range2: [2, 5]
intermittent_edges_color_shift_range2: [-20, 20]
kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
kernel_prob2: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
sinc_prob2: 0.1
blur_sigma2: [0.1, 0.5]
betag_range2: [0.1, 0.5]
betap_range2: [0.1, 0.5]

# Параметры изменения размера и шумов
resize_prob: [0.2, 0.7, 0.1]
resize_range: [0.9, 1.1]
gaussian_noise_prob: 0.1
noise_range: [0, 5]
poisson_scale_range: [0, 0.5]
gray_noise_prob: 0.1
jpeg_range: [30, 95]

# Вторая группа параметров изменения размера и шумов
second_blur_prob: 0.4
resize_prob2: [0.3, 0.4, 0.3]
resize_range2: [0.9, 1.1]
gaussian_noise_prob2: 0.1
noise_range2: [0, 5]
poisson_scale_range2: [0, 0.5]
gray_noise_prob2: 0.1
jpeg_range2: [30, 95]

# Финальные параметры
final_sinc_prob: 0.1