# target class
_target_: src.degradation.ImageDegradationPipeline_custom

# Device (use "cuda" for fast inference)
device: "cuda"

# Scale factor
scale: 2

# Layer intermittent edges
intermittent_edges_prob: 0.5
intermittent_edges_canny_thresholds: [50, 150]
intermittent_edges_length_range: [1, 3]
intermittent_edges_color_shift_range: [-10, 10]

# Layer rainbow effects
rainbow_effects_prob: 0.5
rainbow_effects_edge_width: 15
rainbow_effects_edge_threshold: [10, 150]
rainbow_effects_channel_shift: [10, 50]
rainbow_effects_pixel_randomness_rate: 0.3

# Layer compression artifacts
compression_artifacts_prob: 0.9

# Layer blur
blur_prob: 0.8
kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
kernel_prob: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
blur_sigma: [0.2, 1.5]
betag_range: [0.5, 2]
betap_range: [1, 1.5]
sinc_prob: 0.1

# Layer noise
noise_prob: 0.8
gaussian_noise_prob: 0.5
noise_range: [1, 15]
poisson_scale_range: [0.05, 1.5]
gray_noise_prob: 0.4

# Layer sinc
sinc_layer_prob: 0.2

# Layer jpeg
jpeg_prob: 0.8
jpeg_range: [30, 90]
