train:
  data_object:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.img_augs.CentralCrop
        target_width: 256 # max: 1024 for RealESRGAN, 512 for swin, 256 for ESRT
        target_height: 256 # max: 1024 for RealESRGAN, 512 for swin, 256 for ESRT
