train:
  data_object:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.img_augs.CombinedCrop
        target_width_cc: 512
        target_height_cc: 512
        target_width_rc: 256
        target_height_rc: 256
